# Generated by Django 4.1.2 on 2023-01-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
    ]
