# Generated by Django 4.1.2 on 2023-01-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_skill_options_profile_social_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_cv_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_hired',
            field=models.BooleanField(default=False),
        ),
    ]
