# Generated by Django 4.1.2 on 2022-11-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-review_ratio', '-review_total', 'title']},
        ),
        migrations.AlterField(
            model_name='project',
            name='review_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='review_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
