# Generated by Django 4.1.2 on 2022-11-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_options_alter_project_review_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('very_good', 'Positive Review'), ('good', 'Negative Review')], max_length=255, null=True),
        ),
    ]
