# Generated by Django 4.1.2 on 2023-01-03 02:28

from django.db import migrations, models
import django.db.models.deletion
import projects.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_cv_profile_is_cv_approved_profile_is_hired'),
        ('projects', '0009_alter_review_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=projects.fields.CaseInsensitiveCharField(max_length=500, null=True),
        ),
    ]
