# Generated by Django 4.1.2 on 2023-01-19 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_invitation_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
    ]
