# Generated by Django 4.1.2 on 2023-03-19 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_type_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
