# Generated by Django 4.1.2 on 2023-03-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_jobpost_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
